//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkProject.EntityFrameworkModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel
    {
        public int fuel_id { get; set; }
        public Nullable<System.DateTime> fueling_date { get; set; }
        public Nullable<decimal> transaction_amount { get; set; }
        public Nullable<double> fuel_amount { get; set; }
        public Nullable<int> vehicle_id { get; set; }
        public string payment_type { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
